# Generated by Django 4.1.7 on 2023-05-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0004_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Mark',
            field=models.IntegerField(default=0),
        ),
    ]
