# Generated by Django 4.1.7 on 2023-05-03 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0005_student_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Mark',
            new_name='mark',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='studyapp.department'),
        ),
    ]
