# Generated by Django 4.1.7 on 2023-05-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0006_rename_mark_student_mark_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mark',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
