# Generated by Django 4.1.7 on 2023-05-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0007_alter_student_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mark',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
