# Generated by Django 4.1.7 on 2023-05-04 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0008_alter_student_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='studyapp.user'),
            preserve_default=False,
        ),
    ]
