# Generated by Django 4.1.7 on 2023-05-04 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0009_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to='studyapp.user'),
            preserve_default=False,
        ),
    ]
