# Generated by Django 4.1.7 on 2023-05-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0011_remove_student_mark_remove_studentenrollment_classid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentEnrollment',
        ),
    ]
