# Generated by Django 4.1.7 on 2023-05-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0013_remove_studentenrollment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollTime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='gradeTime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
